import "./globals.css";
import Provider from "../components/Providers";

interface Props {
  children: React.ReactNode;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="bg-[#13131a]">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
